name: Update Navigation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Navigation
        run: |
          echo '- [Contributing](./CONTRIBUTING.md)' > .github/pages/index.md
          echo '- [Changelog](./CHANGELOG.md)' >> .github/pages/index.md
        shell: bash

      - name: Commit Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .github/pages/index.md
          git commit -m "Update navigation" || exit 0
          git push
