name: Update Widgets

on:
  push:
    branches:
      - main

jobs:
  update-widgets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Widget Generator
        run: |
          # Zde spusťte kód nebo skript pro generování widgetů nebo aktualizaci informací.

